name: Generate GitHub Trophies

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: sakshipatil-hue
          output_path: assets/trophies.svg
          theme: darkhub
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Trophy SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update GitHub trophies"
          add: "assets/trophies.svg"
